# Generated by Django 4.2 on 2025-08-11 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=80, unique=True)),
                ('vendor_email', models.EmailField(blank=True, default='vendor@bftt.com', max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, default='+23305000000', max_length=20)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='images/categories')),
                ('description', models.TextField(blank=True, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('vendoruser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'vendor',
                'verbose_name_plural': 'vendors',
            },
        ),
    ]
